### ISSUE TITLE
Elecom Huge

### ISSUE THREAD

**Issue by CommunistWitchDoctor** [cpetrov/deft#2]
The Elecom Huge is more or less a sister to the DEFT trackballs with the same button issues, but doesn't seem to work with this package. Any chance of support or just out of scope?

**Comment by cpetrov** [comment]
I'd prefer not to offer support for it in this repository, since it is not part of the DEFT series.

**Comment by Sqwrly** [comment]
I know you already said you prefer not to put it in this repo but I was hoping maybe you would consider it again. https://patchwork.kernel.org/patch/9987651/ The patch was updated by someone else to add huge support because it apparently behaves the same as the deft.

**Comment by cpetrov** [comment]
@JRussell Linux 4.14 now includes support for Huge.
